# Generated by Django 2.1.2 on 2019-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gracz', models.CharField(choices=[(0, 'Administrator'), (1, 'Browar'), (2, 'Dystrybutor'), (3, 'Hurtownik'), (4, 'Detalista')], max_length=10)),
            ],
        ),
    ]
