# Generated by Django 2.2.4 on 2019-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runda', models.FloatField()),
                ('mag_przed', models.FloatField()),
                ('tow_odb', models.FloatField()),
                ('koszt_tow', models.FloatField()),
                ('tow_wys', models.FloatField()),
                ('dochod', models.FloatField()),
                ('mag_po', models.FloatField()),
                ('koszt_mag', models.FloatField()),
                ('otw_zam', models.FloatField()),
                ('przy_zam', models.FloatField()),
                ('zreli_zam', models.FloatField()),
                ('otw_zam_po', models.FloatField()),
                ('koszt_otw_zam', models.FloatField()),
                ('budzet', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
